version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - intrange
    - ireturn
    - modernize
    - nonamedreturns
    - testpackage
    - varnamelen
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    funlen:
      lines: 65
    gocritic:
      enabled-tags:
        - performance
        - opinionated
        - diagnostic
        - style
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - funlen
          - gosec
          - unparam
        path: ._test\.go
      - linters:
          - gocritic
        path: path.go
        text: appendAssign
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
