run:
  allow-parallel-runners: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - forcetypeassert
    - nonamedreturns
    - exhaustruct
    - testpackage
    - varnamelen
    - intrange
    - depguard
    - ireturn
    - gofumpt

linters-settings:
  govet:
    enable-all: true
  funlen:
    lines: 65
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - funlen
        - cyclop
        - gosec
        - unparam
    - path: path.go
      text: "appendAssign"
      linters:
        - gocritic
