run:
  allow-parallel-runners: true
  go: '1.19'

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - forcetypeassert
    - nonamedreturns
    - exhaustruct
    - testpackage
    - structcheck
    - varnamelen
    - depguard
    - ireturn
    - gofumpt

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
  funlen:
    lines: 65
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - funlen
        - cyclop
    - path: path.go
      text: "appendAssign"
      linters:
        - gocritic
